# permissions for end users to edit reconciliationplans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: reconciliationplan-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubeblocks
    app.kubernetes.io/part-of: kubeblocks
    app.kubernetes.io/managed-by: kustomize
  name: reconciliationplan-editor-role
rules:
- apiGroups:
  - view.kubeblocks.io
  resources:
  - reconciliationplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - view.kubeblocks.io
  resources:
  - reconciliationplans/status
  verbs:
  - get
