apiVersion: apps.kubeblocks.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app.kubernetes.io/name: rollout
    app.kubernetes.io/instance: rollout-sample
    app.kubernetes.io/part-of: kubeblocks
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubeblocks
  name: rollout-sample
spec:
  # TODO(user): Add fields here
